apiVersion: v1
kind: Service # Create service
metadata:
  name: solr-service # Sets the service name
  labels:
    app: solr-service # Defines app to create service for
spec:
  ports:
    - port: 8983
      name: ewb-solr
  selector:
    app: solr-service