apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: ewb-zoo-data-claim # Sets PVC's name
  labels:
    app: ewb-external-backend-apis # Defines app to create PVC for
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Sets PVC's size
